In [1]:
import numpy as np
from sklearn.metrics import accuracy_score

In [2]:
def get_OR_data():
  X=np.array([
      [0,0],
      [0,1],
      [1,0],
      [1,1]
  ])
  Y=np.array([0,1,1,1])
  return X,Y

def get_AND_data():
  X=np.array([
      [0,0],
      [0,1],
      [1,0],
      [1,1]
  ])
  Y=np.array([0,0,0,1])
  return X,Y

def get_NOR_data():
  X=np.array([
      [0,0],
      [0,1],
      [1,0],
      [1,1]
  ])
  Y=np.array([1,0,0,0])
  return X,Y

def get_NAND_data():
  X=np.array([
      [0,0],
      [0,1],
      [1,0],
      [1,1]
  ])
  Y=np.array([1,1,1,0])
  return X,Y

In [3]:
class MyPerceptron:

  def __init__(self,learning_rate=0.1,n_iterations=1000):
    self.lr=learning_rate
    self.epochs=n_iterations
    self.weights=None
    self.bias=None

  def fit(self,X,Y):
    n_features=X.shape[1]
    self.weights=np.zeros(n_features)
    self.bias=0

    for epoch in range(self.epochs):
      for i in range(X.shape[0]):
        Y_pred=self.Step_activation(np.dot(X[i],self.weights)+self.bias)
        mae=Y[i]-Y_pred
        self.weights+=self.lr*mae*X[i]
        self.bias+=self.lr*mae

  def predict(self,X):
    outputs = []
    for i in range(X.shape[0]):
      y_pred=self.Step_activation(np.dot(X[i],self.weights)+self.bias)
      outputs.append(y_pred)
    return np.array(outputs)

  def Step_activation(self, activation):
    if (activation>=0):
      return 1
    else:
      return 0

In [4]:
def run_gate(gate_name,X,Y):
  model=MyPerceptron(learning_rate=0.1, n_iterations=100)
  model.fit(X,Y)
  predictions=model.predict(X)
  print(gate_name)
  print(X)
  print("Predictions:",predictions)
  print("Accuracy:",accuracy_score(Y,predictions))

In [5]:
X1,Y1=get_OR_data()
X2,Y2=get_AND_data()
X3,Y3=get_NOR_data()
X4,Y4=get_NAND_data()

run_gate("OR",X1,Y1)
run_gate("AND",X2,Y2)
run_gate("NOR",X3,Y3)
run_gate("NAND",X4,Y4)

OR
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Predictions: [0 1 1 1]
Accuracy: 1.0
AND
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Predictions: [0 0 0 1]
Accuracy: 1.0
NOR
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Predictions: [1 0 0 0]
Accuracy: 1.0
NAND
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Predictions: [1 1 1 0]
Accuracy: 1.0
